workflows:
  my-workflow:
    publishing:
      google_play:
        credentials: $GCLOUD_KEY_FILE
        track: production
        in_app_update_priority: 0
        changes_not_sent_for_review: false
