// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzlleBJFoSE302pDWtHA0kirQeiSkf-PA',
    appId: '1:9966309706:web:f8198a5cf8786cd6cbb1b3',
    messagingSenderId: '9966309706',
    projectId: 'rememberzap-f4900',
    authDomain: 'rememberzap-f4900.firebaseapp.com',
    storageBucket: 'rememberzap-f4900.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTpslK7poX1wHQQPSyVKxH0HnG1OcH-WM',
    appId: '1:9966309706:android:36889e1b77494880cbb1b3',
    messagingSenderId: '9966309706',
    projectId: 'rememberzap-f4900',
    storageBucket: 'rememberzap-f4900.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7-tkHYNJ-Lz3uJdexuZnALRsMmXVsPck',
    appId: '1:9966309706:ios:b4140dd84faf455dcbb1b3',
    messagingSenderId: '9966309706',
    projectId: 'rememberzap-f4900',
    storageBucket: 'rememberzap-f4900.appspot.com',
    iosClientId: '9966309706-a68hnovjtnusdeern4iqklc9aq4mnpvp.apps.googleusercontent.com',
    iosBundleId: 'com.ThiagoAlves.RememberZap',
  );
}
